version: '3.8'

services:
  chat-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DIALOGS_COUNT=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/dialogs"]
      interval: 30s
      timeout: 10s
      retries: 3